# Generated by Django 5.1.2 on 2025-03-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
        ('Student', '0002_delete_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
