# Generated by Django 5.1.2 on 2025-04-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Index.user')),
                ('teacher_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
            ],
            bases=('Index.user',),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=20, unique=True)),
                ('building_name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('schedule', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Teacher.teacher')),
            ],
        ),
    ]
