# Generated by Django 5.2 on 2025-04-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='joined_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'joined_class', 'date')},
        ),
    ]
